default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

azure_event_hub:
  filter:
    include_entities:
      - sensor.xcel_itron_5_instantaneous_demand_value

logger:
  default: warning
  logs:
    homeassistant.components.azure_event_hub: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.160.198
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5